" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2016 Jul 28
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.

if v:progname =~? "evim"
	finish
endif

set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

call plug#begin($XDG_CONFIG_HOME . '/vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'funorpain/vim-cpplint'
Plug 'StanAngeloff/php.vim'
Plug 'stephpy/vim-php-cs-fixer'
Plug 'neomake/neomake'
Plug 'pangloss/vim-javascript'
Plug 'NLKNguyen/papercolor-theme'
Plug 'sjl/badwolf'
Plug 'ap/vim-css-color'
Plug 'chriskempson/base16-vim'
Plug 'ayu-theme/ayu-vim'
call plug#end()

if has("vms")
	set nobackup		" do not keep a backup file, use versions instead
else
	set backup		" keep a backup file (restore to previous version)
	if has('persistent_undo')
		set undofile	" keep an undo file (undo changes after closing)
	endif
endif

set expandtab tabstop=2 shiftwidth=2
set undodir=$XDG_DATA_HOME/vim/undo
set backupdir=$XDG_DATA_HOME/vim/backup
set directory=$XDG_DATA_HOME/vim/swap
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo

set termguicolors
"set t_Co=256
syntax enable
if $THEME == "light"
  let ayucolor="dark"
  colorscheme ayu
elseif $THEME == "dark"
  colorscheme badwolf
endif
hi! Normal ctermbg=NONE guibg=NONE

cnoremap w!! w !sudo tee > /dev/null %
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

au BufWritePost vimrc so $XDG_CONFIG_HOME/vim/vimrc
